// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveWithJoystick.h"
#include "Commands/LoadDart.h"
#include "Commands/LoadPosition.h"
#include "Commands/RunShooter.h"
#include "Commands/StowPosition.h"
#include "Commands/UnloadPosition.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystick.reset(new Joystick(0));
    
    shootGun.reset(new JoystickButton(joystick.get(), 1));
    shootGun->WhenPressed(new LoadDart());
    runGun.reset(new JoystickButton(joystick.get(), 2));
    runGun->WhileHeld(new RunShooter());
    stow.reset(new JoystickButton(joystick.get(), 11));
    stow->WhenPressed(new StowPosition(-80));
    unload.reset(new JoystickButton(joystick.get(), 9));
    unload->WhenPressed(new UnloadPosition(0));
    load.reset(new JoystickButton(joystick.get(), 7));
    load->WhenPressed(new LoadPosition(0));

    // SmartDashboard Buttons
    SmartDashboard::PutData("DriveWithJoystick", new DriveWithJoystick());
    SmartDashboard::PutData("StowPosition: setpoint", new StowPosition(-80));
    SmartDashboard::PutData("UnloadPosition: setpoint", new UnloadPosition(-157.5));
    SmartDashboard::PutData("LoadPosition: setpoint", new LoadPosition(0));
    SmartDashboard::PutData("LoadDart", new LoadDart());
    SmartDashboard::PutData("RunShooter", new RunShooter());
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getJoystick() {
   return joystick;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
